#!/bin/bash
for i in {1..15}
do
	ping 172.19.223.$i -w 1 > /dev/null
	if  [ $? -eq 0 ]; then
	
	nc -zv -w 1 172.19.223.$i 22
	nc -zv -w 1 172.19.223.$i 80
	
	
	var a = hostname 172.19.223.$i
	
	echo hostname
	
	
	#else
	#	echo "RPI0$i is unresponsive"
	#fi
done






#for i in {10..20}
#do

	#ping rpi$i -w 1 > /dev/null
	#if  [ $? -eq 0 ]; then
	#	echo "RPI$i is responsive"
	#else
	#	echo "RPI$i is unresponsive"
	#fi
#done

echo "done" 
