#!/bin/bash

IpAddress=`hostname -I`

StartVar=`echo "$IpAddress"` | cut -c 1
EndVar=${IpAddress##$StartVar*.}
FinalIpAddress=${IpAddress%$EndVar}

counter=1
until [ $counter -gt 255 ]
do
	UpdateIP="$FinalIpAddress$counter"
	if ping -c 1 -W 1 "$UpdateIP" >/dev/null 2>&1; then
		echo $UpdateIP : alive
		host=`host $UpdateIP | cut -d' ' -f5`
		echo "host : $host"
		File_MacAddress=`grep $UpdateIP /proc/net/arp`
		MacAddress=`echo $File_MacAddress | cut -d' ' -f4`
		echo "Mac Address : $MacAddress"
		if nc -z -w 1 $UpdateIP 22; then
			echo "Port 22 : Open"
		else
			echo "Port 22 : Closed"
		fi
		if nc -z -w 1 $UpdateIP 80; then
			echo "Port 80 : Open"
		else
			echo "Port 80 : Closed"
		echo " "
		fi
	fi
((counter++))
done
