#!/bin/bash
for i in {1..255}
do
	ping 172.19.223.$i -w 1 > /dev/null
	if  [ $? -eq 0 ]; then
	
	nc -zv -w 1 172.19.223.$i port 22
	nc -zv -w 1 172.19.223.$i port 80
	
	
	var b = hostname 172.19.223.$i
	
	echo hostname
	
	
	else
		echo "RPI0$i is unresponsive"
	fi
done






for i in {10..20}
do

	ping rpi$i -w 1 > /dev/null
	if  [ $? -eq 0 ]; then
		echo "RPI$i is responsive"
	else
		echo "RPI$i is unresponsive"
	fi
done

echo "done"
