#!/bin/bash

echo "Enter which pi's"
read PiVar      #this stores the user's input as a variable

if [ "$PiVar" == "" ]; then     #creates an if statement which goes into a$
        for num in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 1$
        do
                if ping -c 1 -W 1 "RPI$num" >/dev/null 2>&1; then   #pings$
                        echo RPI$num : alive
                else
                        echo RPI$num : dead
                fi
        done

else
        if ping -c 1 -W 1 "$PiVar" >/dev/null 2>&1; then
                echo $PiVar : alive                                     #p$
        else
                echo $PiVar : dead
        fi
fi
